<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Medzo.PurchasingSupplier.Application\Medzo.PurchasingSupplier.Application.csproj" />
    <ProjectReference Include="..\..\src\Medzo.PurchasingSupplier.Domain\Medzo.PurchasingSupplier.Domain.csproj" />
  </ItemGroup>
</Project>
