<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\Medzo.PurchasingSupplier.Application\Medzo.PurchasingSupplier.Application.csproj" />
    <ProjectReference Include="..\Medzo.PurchasingSupplier.Infrastructure\Medzo.PurchasingSupplier.Infrastructure.csproj" />
  </ItemGroup>
</Project>
